altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  02cd0416-77db-4b82-9942-1a690d713c47:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 524f4d2f-e713-4d17-9cf2-eec2eb06e5ba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 910938e6-e642-466a-b56a-f1518caf458a
        userCondition: null
fs: filesyetempath
handle: imageUpload
name: image-upload
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
